version : "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herder_container
    ports:
      - '127.0.0.1:3000:3000'
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next